<a href="https://colab.research.google.com/github/girijahota/Python/blob/main/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
## Heading

## initially Lets import numpy

import numpy as np
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)
print(arr)

[1 2 3 4 5]


In [96]:
type(arr)

numpy.ndarray

In [97]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [98]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [99]:
type(arr)

numpy.ndarray

In [100]:
## check the shape of the array

arr.shape

(3, 5)

***Indexing***

In [101]:
## Accessing the array elements

arr.shape

(3, 5)

In [102]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [103]:
arr.shape

(3, 5)

In [104]:
arr[1:,:2]

arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [105]:
arr[:,:3]

array([[1, 2, 3],
       [2, 3, 4],
       [9, 7, 6]])

In [106]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [107]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [108]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
arr[3]

4

In [110]:
arr[3:]=100

In [111]:
arr1=arr

In [112]:
arr1[3:]=500
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [113]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [114]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [115]:
arr

array([   1,    2,    3, 1000, 1000, 1000, 1000, 1000, 1000])

In [116]:
### Some conditions very useful in Exploratory Data Analysis 

val=2

arr[arr<3]

array([1, 2])

In [117]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [118]:
arr1=np.arange(0,10).reshape(2,5)

In [119]:
arr2=np.arange(0,10).reshape(2,5)

In [120]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [121]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [122]:
## random distribution
np.random.rand(3,3)

array([[0.65438327, 0.94208533, 0.11718595],
       [0.01450439, 0.82291519, 0.72387381],
       [0.24861147, 0.17292519, 0.63433271]])

In [123]:
arr_ex=np.random.randn(4,4)

In [124]:
arr_ex

array([[ 0.42604725, -0.0318445 ,  0.80161392,  0.49345327],
       [ 0.07181336,  0.10784562, -0.50203272, -1.04879839],
       [ 0.62015916,  0.69602854,  0.32176983,  1.69195814],
       [ 0.87808248, -0.90542765, -0.89235828, -0.88338472]])

In [130]:
import seaborn as sns
##sns.distplot(pd.DataFrame(arr_ex.reshape(16,1)))

In [126]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [132]:
arr1[3:]=100

In [133]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [128]:
  arr[0:2,0:2]

IndexError: ignored